#!/bin/bash


function suffix2mask() {
	res=$1
	res=${res/\/32/ 255.255.255.255}
	res=${res/\/31/ 255.255.255.254}
	res=${res/\/30/ 255.255.255.252}
	res=${res/\/29/ 255.255.255.248}
	res=${res/\/28/ 255.255.255.240}
	res=${res/\/27/ 255.255.255.224}
	res=${res/\/26/ 255.255.255.192}
	res=${res/\/25/ 255.255.255.128}
	res=${res/\/24/ 255.255.255.0}
	res=${res/\/23/ 255.255.254.0}
	res=${res/\/22/ 255.255.252.0}
	res=${res/\/21/ 255.255.248.0}
	res=${res/\/20/ 255.255.240.0}
	res=${res/\/19/ 255.255.224.0}
	res=${res/\/18/ 255.255.192.0}
	res=${res/\/17/ 255.255.128.0}
	res=${res/\/16/ 255.255.0.0}
	res=${res/\/15/ 255.254.0.0}
	res=${res/\/14/ 255.252.0.0}
	res=${res/\/13/ 255.248.0.0}
	res=${res/\/12/ 255.240.0.0}
	res=${res/\/11/ 255.224.0.0}
	res=${res/\/10/ 255.192.0.0}
	res=${res/\/9/ 255.128.0.0}
	res=${res/\/8/ 255.0.0.0}
	echo $res
}


function networkSuffix() {
	echo $1|cut -d'/' -f2
}

#поиск сертификата по CN в исторической раскладке (*.pem, выданные до этих скриптов)
# $1 - имя (CN)
# $2 - каталог (например ./certs или ./certs/revoked)
function findCertByCN() {
	[ -d "$2" ] || return 0
	for f in "$2"/*.pem; do
		[ -e "$f" ] || continue
		#парсим CN независимо от состава subject и версии openssl (CN = x / CN=x)
		name=`openssl x509 -in $f -noout -subject | sed -E 's|.*CN ?= ?([^,/]*).*|\1|' | tr -d ' '`
		if [ "$name" = "$1" ]; then
			echo $f
			return 0
		fi
	done
}

#функции обмена с инвентори переехали в _lib.inv



# === модель инстансов ===
# инстанс - первоклассная сущность доступа. Вырожденный случай - отсутствие
# списка $instances: тогда используется дефолтный список из одного инстанса
# "local", чьи атрибуты берутся из legacy-переменных
# (srvaddr/port/proto/vpnnet/subnets/dns/use2fa), а имена файлов - без суффикса
# (ccd, <prefix>_<CN>.ovpn, server.conf). Отдельного флага "режима" нет:
# тривиальный режим получается заданием дефолтов и fallback'ом в inst_var /
# пустым суффиксом в instFileSuffix.

# список инстансов: из $instances, пусто - дефолтный список ["local"]
function getInstances() {
	if [ -n "$instances" ]; then
		echo $instances
	else
		echo local
	fi
}

# имя bash-переменной атрибута $2 инстанса $1: '-' в имени недопустим в
# переменной, заменяется на '_' (local-2fa -> local_2fa_<attr>)
function instVarName() {
	echo "$(echo "$1" | tr '-' '_')_$2"
}

# значение атрибута $2 инстанса $1.
# приоритет: <instance>_<attr>, затем дефолт из legacy-переменных. В вырожденном
# случае (instances не задан) legacy-переменные и есть конфиг дефолтного
# инстанса "local", поэтому fallback и возвращает "тривиальный режим".
function inst_var() {
	local inst=$1 attr=$2
	local name=$(instVarName "$inst" "$attr")
	local val=${!name}
	if [ -n "$val" ]; then
		echo "$val"
		return 0
	fi
	case "$attr" in
		addr)           echo "${srvaddr:-}";;
		port)           echo "${port:-1194}";;
		proto)          echo "${proto:-udp}";;
		lan)            echo "${vpnnet:-}";;
		routes)         echo "${subnets:-}";;
		dns)            echo "${dns:-}";;
		previous_lan)   echo "${previousVpnnet:-}";;
		previous_routes) echo "${previousSubnets:-}";;
		auth_mode)      if [ "$use2fa" = "1" ]; then echo "2fa"; else echo "normal"; fi;;
		ccd_dir)        echo "${ovpndir:-}/ccd";;
		delivery)       echo "local";;
		inv_prefix)     echo "ovpn-";;
		ssh_key)        echo "${rsynckeyfile:-}";;
		*)              echo "";;
	esac
}

# суффикс имени файлов инстанса $2: в вырожденном случае (instances не задан)
# суффикс пустой - имена как в старом одиночном варианте. $1 - разделитель:
# "." для CCD (ccd.<instance>), "_" для клиентского конфига, "-" для server-конфига.
function instFileSuffix() {
	if [ -z "$instances" ]; then
		echo ""
	else
		echo "$1$2"
	fi
}

#путь к папке конфига клиента $1 (clientsDir переопределяется в _config,
#по умолчанию - раскладка базового варианта)
function getConfigDir() {
	echo ${clientsDir:-$ovpndir/clients}/$prefix-$1
}

#путь к ccd файлу клиента $1 для инстанса $2: в вырожденном случае - ccd,
#в multi-instance - ccd.<instance>
function getConfigCcd() {
	local user=$1 inst=${2:-}
	echo $(getConfigDir $user)/ccd$(instFileSuffix . "$inst")
}

#получить IP адрес из CCD (учитывает отключенный $ccd.disabled)
# $1 - путь к CCD
function getCcdIp() {
	local ccd=$1
	if [ -s $ccd.disabled ]; then
		ccd=$1.disabled
	fi
	if [ -s $ccd ]; then
		grep -vE '^#' $ccd | grep 'ifconfig-push' | head -n 1 | cut -d' ' -f2
	fi
}
