#!/bin/bash


function suffix2mask() {
	res=$1
	res=${res/\/32/ 255.255.255.255}
	res=${res/\/31/ 255.255.255.254}
	res=${res/\/30/ 255.255.255.252}
	res=${res/\/29/ 255.255.255.248}
	res=${res/\/28/ 255.255.255.240}
	res=${res/\/27/ 255.255.255.224}
	res=${res/\/26/ 255.255.255.192}
	res=${res/\/25/ 255.255.255.128}
	res=${res/\/24/ 255.255.255.0}
	res=${res/\/23/ 255.255.254.0}
	res=${res/\/22/ 255.255.252.0}
	res=${res/\/21/ 255.255.248.0}
	res=${res/\/20/ 255.255.240.0}
	res=${res/\/19/ 255.255.224.0}
	res=${res/\/18/ 255.255.192.0}
	res=${res/\/17/ 255.255.128.0}
	res=${res/\/16/ 255.255.0.0}
	res=${res/\/15/ 255.254.0.0}
	res=${res/\/14/ 255.252.0.0}
	res=${res/\/13/ 255.248.0.0}
	res=${res/\/12/ 255.240.0.0}
	res=${res/\/11/ 255.224.0.0}
	res=${res/\/10/ 255.192.0.0}
	res=${res/\/9/ 255.128.0.0}
	res=${res/\/8/ 255.0.0.0}
	echo $res
}


function networkSuffix() {
	echo $1|cut -d'/' -f2
}

function inventoryGetUnusedIp() {
	network=$1
	mask=`networkSuffix $1`

	invData=`curl -k -s $inventoryApiUrl/net-ips/first-unused?text_addr=$network`
	addr=`echo $invData | jq -r .text_addr`

	if [ "$addr" == "null" ]; then
		&>2 echo "ERR fetching addr: $inventoryApiUrl/net-ips/first-unused?text_addr=$vpnnet"
		exit 10
	fi

	suffix2mask $addr/$mask
}


function inventoryGetPinnedIp() {
	invData=`curl -k -s $inventoryApiUrl/net-ips/search?name=$1`
	echo $invData | jq -r .text_addr
}


