#!/bin/bash

#путь к конфигу $1
function getConfigDir() {
	echo $SCRIPTPATH/clients/$prefix-$1
}

#путь к ccd файлу конфига $1 сайта $2
function getConfigCcd() {
	echo $(getConfigDir $1)/ccd.$2
}

#конвертировать конфиг orgname-ivan-ivanov.v-notebook -> ais-pupkin
function getConfigUser() {
	configDir=`getConfigDir $1`
	configUsernameFile=$configDir\username.txt
	if [ -s $configUsernameFile ]; then
		cat $configUsernameFile
	else
		user=`echo $1|cut -d- -f1`
		#если имя не содержит точки, то предполагаем что это префикс
		if [[ $user == *"."* ]]; then
			echo $user
		else
			echo $1|cut -d- -f1-2
		fi
	fi
}

#получить IP адрес из CCD
# $1 - путь к CCD
# #2 - проверять также $ccd.disabled
function getCcdIp() {
	ccd=$1
	if [ -s $ccd.disabled ]; then
		ccd=$1.disabled
	fi
	if [ -s $ccd ]; then
		grep -vE '^#' $ccd | grep 'ifconfig-push' | head -n 1 | cut -d' ' -f2
	fi
}

#192.168.0.0/24 -> 192.168.0.0 255.255.255.0
function suffix2mask() {
	res=$1
	res=${res/\/32/ 255.255.255.255}
	res=${res/\/31/ 255.255.255.254}
	res=${res/\/30/ 255.255.255.252}
	res=${res/\/29/ 255.255.255.248}
	res=${res/\/28/ 255.255.255.240}
	res=${res/\/27/ 255.255.255.224}
	res=${res/\/26/ 255.255.255.192}
	res=${res/\/25/ 255.255.255.128}
	res=${res/\/24/ 255.255.255.0}
	res=${res/\/23/ 255.255.254.0}
	res=${res/\/22/ 255.255.252.0}
	res=${res/\/21/ 255.255.248.0}
	res=${res/\/20/ 255.255.240.0}
	res=${res/\/19/ 255.255.224.0}
	res=${res/\/18/ 255.255.192.0}
	res=${res/\/17/ 255.255.128.0}
	res=${res/\/16/ 255.255.0.0}
	res=${res/\/15/ 255.254.0.0}
	res=${res/\/14/ 255.252.0.0}
	res=${res/\/13/ 255.248.0.0}
	res=${res/\/12/ 255.240.0.0}
	res=${res/\/11/ 255.224.0.0}
	res=${res/\/10/ 255.192.0.0}
	res=${res/\/9/ 255.128.0.0}
	res=${res/\/8/ 255.0.0.0}
	echo $res
}


function networkSuffix() {
	echo $1|cut -d'/' -f2
}

#конвертирует IP адрес из сети 2FAopenvpn в сеть openvpn того же филиала
#$1 - IP
#$2 - сайт
function 2faToNormalIp() {
	addr=$1
	site=$2

	#формируем переменную mhk__openvpn2fa_lan
	site_ovpn2fa_lan_var=${site}_openvpn2fa_lan
	#получаем значение
	site_ovpn2fa_lan=${!site_ovpn2fa_lan_var}
	#если такая переменная есть (а не везде для 2FA отдельные сети), то подменяем префиксы IP
	if [ -n "$site_ovpn2fa_lan" ]; then
		site_ovpn_lan_var=${site}_openvpn_lan
		site_ovpn_lan=${!site_ovpn_lan_var}

		site_subnet=`echo $site_ovpn_lan | cut -d'.' -f1-3`
		site_2fasubnet=`echo $site_ovpn2fa_lan | cut -d'.' -f1-3`

		echo $addr |sed "s/^$site_2fasubnet/$site_subnet/"
	else
		echo $addr
	fi
}

#конвертирует IP адрес из сети 2FAopenvpn в сеть openvpn того же филиала
#$1 - IP
#$2 - сайт
function normalTo2faIp() {
	addr=$1
	site=$2

	#формируем переменную mhk__openvpn2fa_lan
	site_ovpn2fa_lan_var=${site}_openvpn2fa_lan
	#получаем значение
	site_ovpn2fa_lan=${!site_ovpn2fa_lan_var}
	#если такая переменная есть (а не везде для 2FA отдельные сети), то подменяем префиксы IP
	if [ -n "$site_ovpn2fa_lan" ]; then
		site_ovpn_lan_var=${site}_openvpn_lan
		site_ovpn_lan=${!site_ovpn_lan_var}

		site_subnet=`echo $site_ovpn_lan | cut -d'.' -f1-3`
		site_2fasubnet=`echo $site_ovpn2fa_lan | cut -d'.' -f1-3`

		echo $addr |sed "s/^$site_subnet/$site_2fasubnet/"
	else
		echo $addr
	fi
}

